apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.1

        ports:
        - containerPort: 5432

        volumeMounts:
        - name: postgres-pv
          mountPath: /var/lib/postgresql/data

        command: ["/usr/sbin/useradd"]
#        args: ["1000"]

        command: ["/usr/sbin/groupadd"]
#        args: ["1000"]

        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-root-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-root-password

      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
